import type { AccountProduct, LaptopProduct } from '@/types/product.type'

export const laptopProducts: LaptopProduct[] = [
  {
    id: 'm1',
    name: 'Dell Latitude 7420 i7',
    price: 22500000,
    thumbnail: '',
    brand: 'Dell',
    cpu: 'Intel Core i7 Gen 11',
    gpu: 'Intel Iris Xe Graphics',
    ram: '16GB DDR4',
    ssd: '512GB NVMe SSD',
    screen: '14 inch Full HD IPS',
    description: 'Laptop doanh nhân siêu bền bỉ, mỏng nhẹ và bảo mật cao. Hiệu năng vượt trội từ chip Intel Core i7 thế hệ 11, phù hợp cho mọi công việc văn phòng và đồ họa nhẹ.',
  },
  {
    id: 'm3',
    name: 'MacBook Pro 14" M3 2024',
    price: 39990000,
    thumbnail: '',
    brand: 'Apple',
    cpu: 'Apple M3 Pro',
    gpu: '14-core GPU',
    ram: '18GB Unified Memory',
    ssd: '512GB SSD',
    screen: '14.2 inch Liquid Retina XDR 120Hz',
    description: 'Siêu phẩm công nghệ mới nhất từ Apple với con chip M3 Pro siêu mạnh mẽ. Màn hình Liquid Retina XDR đỉnh cao và thời lượng pin ấn tượng lên tới 22 tiếng.',
  },
  {
    id: 'm6',
    name: 'HP Envy 13 x360 Mới',
    price: 18500000,
    thumbnail: '',
    brand: 'HP',
    cpu: 'AMD Ryzen 7 5700U',
    gpu: 'AMD Radeon Graphics',
    ram: '16GB DDR4',
    ssd: '512GB NVMe SSD',
    screen: '13.3 inch Full HD OLED Touch',
    description: 'Laptop xoay gập 360 độ cao cấp từ HP. Màn hình OLED cảm ứng sắc nét cùng bút cảm ứng đi kèm, lý tưởng cho những ai thích sáng tạo và vẽ phác thảo.',
  },
  {
    id: 'm8',
    name: 'ThinkPad X1 Carbon Gen 10',
    price: 32000000,
    thumbnail: '',
    brand: 'Lenovo',
    cpu: 'Intel Core i7 Gen 12',
    gpu: 'Intel Iris Xe Graphics',
    ram: '16GB LPDDR5',
    ssd: '512GB NVMe SSD Gen 4',
    screen: '14 inch WUXGA IPS 400 nits',
    description: 'Huyền thoại laptop doanh nhân cao cấp. Chất liệu sợi carbon siêu nhẹ, bàn phím gõ êm ái nhất thế giới và độ bền chuẩn quân đội Mỹ.',
  },
]

export const accountProducts: AccountProduct[] = [
  {
    id: 'm2',
    name: 'Netflix Premium 4K 1 Tháng',
    price: 55000,
    thumbnail: '',
    platform: 'Netflix',
    duration: '1 tháng',
    devices: '1 profile',
    description: 'Tài khoản Netflix Premium hỗ trợ chất lượng hình ảnh Ultra HD 4K và âm thanh vòm Dolby Atmos. Xem trực tiếp trên Tivi, Điện thoại, Máy tính cá nhân.',
  },
  {
    id: 'm4',
    name: 'Adobe Creative Cloud 1 Năm',
    price: 350000,
    thumbnail: '',
    platform: 'Adobe',
    duration: '12 tháng',
    devices: '2 thiết bị',
    description: 'Trọn bộ hơn 20 ứng dụng Adobe chính chủ (Photoshop, Illustrator, Premiere Pro, After Effects...) dung lượng lưu trữ đám mây 80GB Cloud storage.',
  },
  {
    id: 'm5',
    name: 'Adobe Gia hạn chính chủ',
    price: 280000,
    thumbnail: '',
    platform: 'Adobe',
    duration: '12 tháng',
    devices: '2 thiết bị',
    description: 'Gia hạn trực tiếp trên tài khoản Adobe cá nhân chính chủ của bạn. Giữ nguyên mọi dữ liệu đám mây và lịch sử làm việc trước đó.',
  },
  {
    id: 'm7',
    name: 'Spotify Premium 1 Năm',
    price: 290000,
    thumbnail: '',
    platform: 'Spotify',
    duration: '12 tháng',
    devices: '1 tài khoản',
    description: 'Nghe nhạc chất lượng cao không quảng cáo trên Spotify. Tải nhạc ngoại tuyến và cá nhân hóa danh sách phát của bạn.',
  },
]

export const formatPrice = (price: number) => {
  return price.toLocaleString('vi-VN') + 'đ'
}